use bevy::prelude::*;
use serde::{Deserialize, Serialize};
use std::collections::VecDeque;
use crate::components::GridPosition;
use crate::state::Player;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum GameCommand {
    SelectUnit { target: GridPosition },
    MoveUnit { destination: GridPosition },
    Attack { target: GridPosition },
    EndActivation,
}

#[derive(Debug, Clone)]
pub struct NetworkCommand {
    pub sender: Player,
    pub command: GameCommand,
}

#[derive(Resource, Default)]
pub struct CommandQueue {
    // Commands generated by this client. ONLY input.rs produces this.
    pub outgoing: VecDeque<GameCommand>,

    // Commands waiting for authoritative resolution. ONLY game.rs consumes this.
    pub incoming: VecDeque<NetworkCommand>,
}
